### ISSUE TITLE
[Method 1] 没出现Apple Intelligence & Siri"选项

### ISSUE THREAD

**Issue by playingapi** [Kyle-Ye/XcodeLLMEligible#17]
### Additional Information

设置里面看不到这个选项 "Apple Intelligence & Siri"
![image](https://github.com/user-attachments/assets/77a411d1-52d6-4a6c-b9e4-a9039e417d20)

![image](https://github.com/user-attachments/assets/515dc7d1-cb65-4a17-9c13-9409fd39aa30)
  
log:

 ./override_apple_intelligence.sh
Performing install action...

SIP is disabled.

amfi_get_out_of_my_way=1 is present in boot-args.
🎉 SIP is disabled and amfi_get_out_of_my_way=1 is present in boot-args.

Downloading eligibility_util...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1530k  100 1530k    0     0   720k      0  0:00:02  0:00:02 --:--:-- 2909k
Setting Apple Intelligence to eligible...
Force domain answer successfully
Setting Complete...

Checking the status...
OS_ELIGIBILITY_ANSWER_ELIGIBLE

Apple Intelligence eligible override script install completed.
If you find this script helpful, please consider giving a star to the project.
🌟🌟🌟 https://github.com/Kyle-Ye/XcodeLLMEligible 🌟🌟🌟

**Comment by Kyle-Ye** [comment]
You need to upgrade to macOS 15.1 Beta to fix the issue.

**Comment by fmatrixch** [comment]
You're using 15.0 version......

**Comment by playingapi** [comment]
已升级到15.1 问题已解决  siri不能用 升级了个寂寞

**Comment by fmatrixch** [comment]
> 已升级到15.1 问题已解决 siri不能用 升级了个寂寞

对啊，Siri还是个人工智障。

两个月只写出来一个GUI，林檎团队真有你的。
