### ISSUE TITLE
[Method 1] sudo not found

### ISSUE THREAD

**Issue by taozhiyuai** [Kyle-Ye/XcodeLLMEligible#18]
### Additional Information

禁止SIP后,运行sudo nvram boot-args="amfi_get_out_of_my_way=1",显示sudo not found

Sonoma 14.6

**Comment by taozhiyuai** [comment]
下面的脚本执行,需要在禁用SIP之前在系统里执行?

脚本执行

安装

XcodeLLM:

curl -L https://raw.github.com/Kyle-Ye/XcodeLLMEligible/main/override_xcodellm.sh | bash
Apple Intelligence:

curl -L https://raw.github.com/Kyle-Ye/XcodeLLMEligible/main/override_apple_intelligence.sh | bash
卸载

XcodeLLM:

curl -L https://raw.github.com/Kyle-Ye/XcodeLLMEligible/main/override_xcodellm.sh | bash -s -- uninstall

**Comment by Kyle-Ye** [comment]
> 禁止SIP后,运行sudo nvram boot-args="amfi_get_out_of_my_way=1",显示sudo not found

There is no sudo in Recovery OS. Remove 'sudo' in Recovery OS or reboot into normal OS with SIP disabled and run the command to set boot-args.

> Sonoma 14.6

1. For Xcode LLM: You need macOS 15.0 Beta 1+
2. For Apple Intelligence: You need macOS 15.1 Beta+

> 下面的脚本执行,需要在禁用SIP之前在系统里执行?

You need to disable SIP, set boot-arg and then run the script. Or download the binary and execute it yourself.

**Comment by fmatrixch** [comment]
these scripts actually need you to run after disabling SIP yet

**Comment by taozhiyuai** [comment]
> these scripts actually need you to run after disabling SIP yet

already disabled

**Comment by taozhiyuai** [comment]
![IMG_20240802_182504.jpg](https://github.com/user-attachments/assets/4d823c74-99aa-4d98-8e24-66eb5ef6026f)

**Comment by taozhiyuai** [comment]
run the following after rebooting. not recovery mode

`taozhiyu@603e5f4a42f1 ~ % cd downloads
taozhiyu@603e5f4a42f1 downloads % csrutil status
System Integrity Protection status: disabled.
taozhiyu@603e5f4a42f1 downloads % chmod +x eligibility_util
taozhiyu@603e5f4a42f1 downloads % ./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER --answer 4
dyld[820]: Symbol not found: _os_eligibility_domain_for_name
  Referenced from: <64149775-218A-397B-B3C5-49EAC1FC1032> /Users/taozhiyu/Downloads/eligibility_util
  Expected in:     <ADF6A9D2-C5C3-3A9C-9302-4618D9DFAD21> /usr/lib/system/libsystem_eligibility.dylib
zsh: abort      ./eligibility_util forceDomainAnswer --domain-name  --answer 4`

**Comment by taozhiyuai** [comment]
![IMG_20240802_183946.jpg](https://github.com/user-attachments/assets/efbbe517-73ab-4a4b-ad9e-b445d348f6a9)

in recovery mode without sudo

**Comment by taozhiyuai** [comment]
> > 禁止SIP后,运行sudo nvram boot-args="amfi_get_out_of_my_way=1",显示sudo not found
> 
> There is no sudo in Recovery OS. Remove 'sudo' in Recovery OS or reboot into normal OS with SIP disabled and run the command to set boot-args.
> 
> > Sonoma 14.6
> 
> 1. For Xcode LLM: You need macOS 15.0 Beta 1+
> 2. For Apple Intelligence: You need macOS 15.1 Beta+
> 
> > 下面的脚本执行,需要在禁用SIP之前在系统里执行?
> 
> You need to disable SIP, set boot-arg and then run the script. Or download the binary and execute it yourself.

@Kyle-Ye  maybe I should upgrade to macOS 15.x before I run those commands? v14.6 is not supported?

**Comment by Kyle-Ye** [comment]
Of course. Only macOS 15.x is supported.

**Comment by taozhiyuai** [comment]
> Of course. Only macOS 15.x is supported.

MacOS Sequoia 1.51 beta(15.1 developer beta) or 15 beta 4(developer beta), which on should I choose? @Kyle-Ye

**Comment by Kyle-Ye** [comment]
For Xcode LLM: You need macOS 15.0 Beta 1+
For Apple Intelligence: You need macOS 15.1 Beta+

**Comment by taozhiyuai** [comment]
> For Xcode LLM: You need macOS 15.0 Beta 1+ For Apple Intelligence: You need macOS 15.1 Beta+

I have upgraded to 15.1 beta(24B5009I)

taozhiyu@Mac ~ % csrutil status
System Integrity Protection status: disabled.
taozhiyu@Mac ~ % sudo nvram boot-args="amfi_get_out_of_my_way=1"
Password:
taozhiyu@Mac ~ % cd downloads
taozhiyu@Mac downloads % ./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_XCODE_LLM --answer 4
Force domain answer successfully

it seems there is no apple intelligence  in Siri,system setting. what else should I do next?

**Comment by taozhiyuai** [comment]
taozhiyu@Mac ~ % curl -L https://raw.github.com/Kyle-Ye/XcodeLLMEligible/main/override_xcodellm.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4361  100  4361    0     0  24603      0 --:--:-- --:--:-- --:--:-- 24638
Performing install action...

SIP is disabled.

amfi_get_out_of_my_way=1 is present in boot-args.
🎉 SIP is disabled and amfi_get_out_of_my_way=1 is present in boot-args.

Downloading eligibility_util...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
100 1530k  100 1530k    0     0   8246      0  0:03:10  0:03:10 --:--:-- 11686
Setting XcodeLLM to eligible...
Force domain answer successfully
Setting Complete...

Checking the status...
OS_ELIGIBILITY_ANSWER_ELIGIBLE

XcodeLLM eligible override script install completed.
If you find this script helpful, please consider giving a star to the project.
🌟🌟🌟 https://github.com/Kyle-Ye/XcodeLLMEligible 🌟🌟🌟

**Comment by taozhiyuai** [comment]
> The command you post is for unlocking Xcode LLM.
> 
> If you want to try Apple Intelligence, use `OS_ELIGIBILITY_DOMAIN_GREYMATTER` instead.
> 
> Please check README.md before asking :)
> 
> ```
> ./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER --answer 4
> ```

thanks for help. I have read it. still a little bit confusing for beginner.

I have pressed join waitlist button now. wait for the result.

at the moment , fail to execute curl -L https://raw.github.com/Kyle-Ye/XcodeLLMEligible/main/override_apple_intelligence.sh | bash

stil trying. I think it is connection issue

**Comment by taozhiyuai** [comment]
taozhiyu@Mac downloads % curl -L https://raw.github.com/Kyle-Ye/XcodeLLMEligible/main/override_apple_intelligence.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 1530k  100 1530k    0     0  19316      0  0:01:21  0:01:21 --:--:-- 47350
Setting Apple Intelligence to eligible...
Force domain answer successfully
Setting Complete...

Checking the status...
OS_ELIGIBILITY_ANSWER_ELIGIBLE

Apple Intelligence eligible override script install completed.
If you find this script helpful, please consider giving a star to the project.
🌟🌟🌟 https://github.com/Kyle-Ye/XcodeLLMEligible 🌟🌟🌟

**Comment by taozhiyuai** [comment]
I have waited a night to join the waitlist @_@

**Comment by Kyle-Ye** [comment]
See "Trouble Shooting" section:

- Log in with a US Apple ID
- Set Region to United States and English as the primary language
- Set English (United States) as your Siri language

Also suggest to set global VPN with an US IP address.

**Comment by taozhiyuai** [comment]
> See "Trouble Shooting" section:
> 
> * Log in with a US Apple ID
> * Set Region to United States and English as the primary language
> * Set English (United States) as your Siri language
> 
> Also suggest to set global VPN with an US IP address.

激活以后,正常使用过程中,是否还需要美国的VPN?

**Comment by fmatrixch** [comment]
> > See "Trouble Shooting" section:
> > 
> > * Log in with a US Apple ID
> > * Set Region to United States and English as the primary language
> > * Set English (United States) as your Siri language
> > 
> > Also suggest to set global VPN with an US IP address.
> 
> 激活以后,正常使用过程中,是否还需要美国的VPN?

yep

US VPN only

**Comment by fmatrixch** [comment]
The Apple Intelligence Beta is totally US limited.

**Comment by taozhiyuai** [comment]
> The Apple Intelligence Beta is totally US limited.

OK,thanks.
