### ISSUE TITLE
[Other] Will method1 change the disk security level to 'Permissive Security'?

### ISSUE THREAD

**Issue by SilvaXiang** [Kyle-Ye/XcodeLLMEligible#19]
### Additional Information

Hey, I successfully enable the Apple intelligence via the method1 with the macOS 15.1 beta , but my disk security level is changed to '`Permissive Security`' in which some application can not be opened with the alert `To open this app, you’ll need to start up your Mac from macOS Recovery and change the Security Policy to Full Security or Reduced Security. `. Can such change be ascribed to your given method1?

**Comment by Kyle-Ye** [comment]
Yes. You should reenable SIP as soon as you do not need it.

See Method 1's Step 4 and Step 5. Or you can check Apple's documentation.

https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection?language=objc
