### ISSUE TITLE
[Other] Not working on macOS 15 beta 7 after enabling SiP

### ISSUE THREAD

**Issue by LiYanan2004** [Kyle-Ye/XcodeLLMEligible#21]
### Additional Information

Use eligibility_util v0.2 to enable Xcode Predictive Code Completion works when SiP is disabled, but once re-enable SiP, everything reverts back to normal state, even when I try to lock eligibility.plist file. 

If I disable SiP again and reboot the machine, **without any changes**, the predictive code completion is available.

**Comment by Kyle-Ye** [comment]
1. Which method?
2. ~Please provide OS information.~ Oh. I see it on the title.
3. Both method 1 and method 2 is working by the magic override file. Please confirm whether it exits on your disk or not. (If it did exist and not work, kill eligibilityd to reload it. If not, you can debug yourself on why it is not. https://github.com/Kyle-Ye/eligibility/blob/main/docs/eligibilityd_debug.md)
4. "eligibility.plist" is just a on-the-fly file. Please ignore it... It will trigger a resave at any time.

**Comment by LiYanan2004** [comment]
Let me open a new issue for more specific details
