### ISSUE TITLE
[Method 2] Not working on macOS 15.0 beta 7

### ISSUE THREAD

**Issue by LiYanan2004** [Kyle-Ye/XcodeLLMEligible#22]
### JSON Output

{
    "OS_ELIGIBILITY_DOMAIN_ALUMINUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_ARGON" = 2;
    "OS_ELIGIBILITY_DOMAIN_BERYLLIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_BORON" = 2;
    "OS_ELIGIBILITY_DOMAIN_CALCIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_CARBON" = 2;
    "OS_ELIGIBILITY_DOMAIN_CHLORINE" = 2;
    "OS_ELIGIBILITY_DOMAIN_CHROMIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_COBALT" = 4;
    "OS_ELIGIBILITY_DOMAIN_COPPER" = 2;
    "OS_ELIGIBILITY_DOMAIN_FLUORINE" = 2;
    "OS_ELIGIBILITY_DOMAIN_GREYMATTER" = 2;
    "OS_ELIGIBILITY_DOMAIN_HELIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_HYDROGEN" = 2;
    "OS_ELIGIBILITY_DOMAIN_IRON" = 4;
    "OS_ELIGIBILITY_DOMAIN_KRYPTON" = 2;
    "OS_ELIGIBILITY_DOMAIN_LITHIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_LOTX" = 2;
    "OS_ELIGIBILITY_DOMAIN_MAGNESIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_MANGANESE" = 2;
    "OS_ELIGIBILITY_DOMAIN_NEON" = 2;
    "OS_ELIGIBILITY_DOMAIN_NICKEL" = 2;
    "OS_ELIGIBILITY_DOMAIN_NITROGEN" = 2;
    "OS_ELIGIBILITY_DOMAIN_OXYGEN" = 2;
    "OS_ELIGIBILITY_DOMAIN_PHOSPHORUS" = 2;
    "OS_ELIGIBILITY_DOMAIN_PODCASTS_TRANSCRIPTS" = 2;
    "OS_ELIGIBILITY_DOMAIN_POTASSIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_SCANDIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_SEARCH_MARKETPLACES" = 2;
    "OS_ELIGIBILITY_DOMAIN_SILICON" = 2;
    "OS_ELIGIBILITY_DOMAIN_SODIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_SULFUR" = 2;
    "OS_ELIGIBILITY_DOMAIN_SWIFT_ASSIST" = 2;
    "OS_ELIGIBILITY_DOMAIN_TITANIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_VANADIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_XCODE_LLM" = 2;
    "OS_ELIGIBILITY_DOMAIN_ZINC" = 2;
}

### Upload Compressed Archive

[eligibilityd.zip](https://github.com/user-attachments/files/16687471/eligibilityd.zip)
[os_eligibility.zip](https://github.com/user-attachments/files/16687472/os_eligibility.zip)

### Additional Information

Got this at the end of the script.

> [download_file] Download completed
> [method_override] Checking the status...
> OS_ELIGIBILITY_ANSWER_NOT_ELIGIBLE
> [install] completed

Running macOS 15.0 beta 7.

**Comment by Kyle-Ye** [comment]
Please add your script execution log and try to find and upload the override file in `/private/var/root/Library/Daemon\ Containers/<UUID>/Data/Library/Caches/NeverRestore/eligibility_overrides.data`

**Comment by LiYanan2004** [comment]
### Override file content

<img width="1073" alt="截屏2024-08-21 17 18 06" src="https://github.com/user-attachments/assets/0374bd3d-1d50-4721-b5f0-378bfa622747">

### Full Log

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Pa100  9705  100  9705    0     0  11844      0 --:--:-- --:--:-- --:--:-- 11835

Performing with [action]=install [method]=override [key]=xcodellm
[install] started
[download_file] Download started
[download_file] Downloading from https://github.com/Kyle-Ye/XcodeLLMEligible/releases/download/0.2.0/xcodellm.eligibility_overrides.data to /tmp/eligibility_overrides.data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   540  100   540    0     0    267      0  0:00:02  0:00:02 --:--:--     0
[download_file] Download completed
[method_override] Copying eligibility_overrides.data to each Daemon Container...
[method_override] Copying for container D906A0A6-8102-4C78-9C2F-8176A86E4C2F
[method_override] Copied to /private/var/root/Library/Daemon Containers/D906A0A6-8102-4C78-9C2F-8176A86E4C2F/Data/Library/Caches/NeverRestore/
[method_override] killing eligibilityd...
[download_file] Download started
[download_file] Downloading from https://github.com/Kyle-Ye/XcodeLLMEligible/releases/download/0.2.0/eligibility_util_sip to /tmp/eligibility_util_sip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1529k  100 1529k    0     0   704k      0  0:00:02  0:00:02 --:--:-- 7803k
[download_file] Download completed
[method_override] Checking the status...
OS_ELIGIBILITY_ANSWER_NOT_ELIGIBLE
[install] completed
If you find this script helpful, please consider giving a star to the project.
🌟🌟🌟 https://github.com/Kyle-Ye/XcodeLLMEligible 🌟🌟🌟
```

### Additional Information 

I also checked eligibility log by force kill it and restart again. And I noticed there is a log saying

> -[EligibilityEngine _loadOverridesWithError:]: Failed to decode eligibility overrides: Error Domain=NSCocoaErrorDomain Code=257 UserInfo={NSUnderlyingError=0x558044d50 {Error Domain=NSPOSIXErrorDomain Code=1}, NSFilePath=<private>, NSURL=<private>}

**Comment by luosheng** [comment]
Same here. Here's the override file. 

[eligibility_overrides.data.zip](https://github.com/user-attachments/files/16689816/eligibility_overrides.data.zip)

**Comment by LiYanan2004** [comment]
#### Update

Investigated with @Kyle-Ye.

Seems like we ran into authorization-related issue. 

<img width="1523" alt="截屏2024-08-22 01 15 03" src="https://github.com/user-attachments/assets/867167c9-397a-40fe-b7bc-9e3e479455d6">

- SiP turns off: Everything looks great
- SiP turns on: Operation not permitted

### Pre-conclusion

When system detects the SiP turned on, it refuses to decode override file.

Override file not changes, everything looks the same.

When `eligibilityd` tries to read override file with SiP enabled, it says 'Operation not permitted'. In fact, `eligibilityd` runs as root user and should be able to access those folders.

We cannot infer the logic behind the scene, personally, I think Apple wants to prevent user from modifying the default behavior, but with a ridiculous way. ~~Only Apple can do~~

Let's waiting for next OS release to see if something changes.

**Comment by YanMinMacMaster** [comment]
I am facing the same problem. I tried the second method without turning off SIP. Does the first method work on the latest beta version, or do you have any other ways to solve this issue?

**Comment by Kyle-Ye** [comment]
The preliminary conclusion is that from macOS 15.0 Beta 7, method 1 and method 2 still works but both requires SIP to be kept disabled. macOS 15.1 Beta 2 is not effected currently.

**Comment by YanMinMacMaster** [comment]
curl -L https://raw.githubusercontent.com/Kyle-Ye/XcodeLLMEligible/release/0.2/scripts/override.sh | bash -s -- install util all
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9705  100  9705    0     0   115k      0 --:--:-- --:--:-- --:--:--  115k
Performing with [action]=install [method]=util [key]=all
[install] started
[check_sip_status] checking SIP status...
[check_sip_status] SIP is disabled
[amfi_check] checking boot-args
[amfi_check] amfi_get_out_of_my_way=1 is not present in boot-args
[method_util_check] Please diable SIP and add amfi_get_out_of_my_way=1 to boot-args
[method_util_check] Or you can use 'override' method to install

**Comment by YanMinMacMaster** [comment]
still doesn't work

**Comment by Kyle-Ye** [comment]
> [amfi_check] amfi_get_out_of_my_way=1 is not present in boot-args

Hi, @YanMinMacMaster. The log just shows why it is not working for you.

Please read the [README section](https://github.com/Kyle-Ye/XcodeLLMEligible?tab=readme-ov-file#method-1-util-tool-recommended-1) for detail.

Also I suggest you create a new issue for your case if you have further problem.

**Comment by luosheng** [comment]
I'm on macOS 15.0 beta 8. The checkbox for "predictive code completion" in Xcode works now without the need to rerun the script. 
<img width="830" alt="截屏2024-08-29 13 57 47" src="https://github.com/user-attachments/assets/a209c666-b23a-41ca-addf-7f647050d2b9">

But I encounter an error when downloading the model. I don't know if Xcode adds another level of validation or it's just happening on my machine. It used to work on previous betas.
<img width="612" alt="截屏2024-08-29 13 57 35" src="https://github.com/user-attachments/assets/5c84f4ac-62df-44fa-98b4-fada0a752db1">

**Comment by LiYanan2004** [comment]
> I'm on macOS 15.0 beta 8.

Beta 8 is out? Okay, let me try.

**Comment by LiYanan2004** [comment]
## Update

After updating to 15.0 beta 8, the checkbox of "Predictive Code Completion" is able to be checked.

> Failed to find asset: com.apple.fm.code.generate_safety_guardrail.tokenizer

But failed to download generative model. And this deserves a new issue.

**Comment by LiYanan2004** [comment]
@luosheng This can be resolved by changing your region to America in System Settings -> General -> Language & Region.

**Comment by luosheng** [comment]
@LiYanan2004 Sadly, this still doesn't work. Should we continue this topic in a new issue?

<img width="706" alt="Screenshot 2024-09-01 at 09 31 49" src="https://github.com/user-attachments/assets/5d1a6861-5f3c-4b18-9c86-cd6c1fe8cd4d">

**Comment by LiYanan2004** [comment]
@luosheng Restart your computer after changing the region and try try again. It should work after restarting

**Comment by luosheng** [comment]
@LiYanan2004 I did. I even did a full reinstall of the script and it still didn't work. If it works on your machine, I'm guessing some other actions make the difference.

**Comment by LiYanan2004** [comment]
Have you ever downloaded the model before? If so, it should have some cache and after setting the region. It will automatically use that model. If you never downloaded the model before, that might have some other issues. Please file a new issue

**Comment by LiYanan2004** [comment]
I don't know. I just change the region and language to English(US) and restart my computer. And it works, and I tried to set language to simplified Chinese and restarting my device. Still works.

**Comment by Atticus5159** [comment]
I used the second method to override without SIP's prohibition. I installed successfully, but my "predictive code completion" is still grawy color. My MacOS is 15.0, and I did not turn off SIP. I don't know why. Would anyone help me out? @LiYanan2004 @Kyle-Ye I really appreciate.

**Comment by Atticus5159** [comment]
I solved my problem by using link which only override the XcodeLLM. It works now. But when I use the override for all, XcodeLLM still cannot work. I don't know why. Is the reason that I need to wait the MacOS 15.1 RELEASE VERSION?

**Comment by LiYanan2004** [comment]
@Atticus5159 you’re right. Kyle has added notes in README.

https://github.com/Kyle-Ye/XcodeLLMEligible/issues/28#issuecomment-2362575713

**Comment by Atticus5159** [comment]
> @Atticus5159 you’re right. Kyle has added notes in README.
> 
> [#28 (comment)](https://github.com/Kyle-Ye/XcodeLLMEligible/issues/28#issuecomment-2362575713)

Thanks for your reply. It is a big help. I'll wait MacOS 15.1. U G.O.A.T(Greatest of all time)
