### ISSUE TITLE
[Other] A necessary step to activate Clean Up (Part of Apple Intelligence on MacOS 15.1 Beta 3)

### ISSUE THREAD

**Issue by TosJojan** [Kyle-Ye/XcodeLLMEligible#24]
### Additional Information

Manual Execution of [Method 1]
When executing the commands of [eligibility_util], additionally execute [./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_STRONTIUM --answer 4].
It works when SIP is activated.

**Comment by MiKayule** [comment]
What is the behavior of "Strontium"? I didn't find any detailed information about it on the Internet. [https://theapplewiki.com/wiki/Eligibility](The Apple Wiki) site doesn't have anything about Strontium.

**Comment by Kyle-Ye** [comment]
It is possibly the domain to unlock Clean Up as part of Apple Intelligence in the latest beta according to the OP.

And I'll upgrade my Mac and confirm it later.

**Comment by TosJojan** [comment]
> What is the behavior of "Strontium"? I didn't find any detailed information about it on the Internet. [The Apple Wiki](https://theapplewiki.com/wiki/Eligibility) site doesn't have anything about Strontium.

There is no such domain “STRONTIUM” in MacOS 15.0 beta 8.
It was possibly only added in the latest MacOS 15.1 Beta 3.

**Comment by KathrineHo1999** [comment]
请问会有Interl版本的eligibility_util_sip 文件吗

**Comment by Kyle-Ye** [comment]
> 请问会有Interl版本的eligibility_util_sip 文件吗

No plan yet.

You can follow the script to build it yourself on your intel Mac.

https://github.com/Kyle-Ye/eligibility/blob/2fe29d014b38a1c2b55556e41720d5091e5da440/.github/workflows/publish_release.yml#L21-L34
