### ISSUE TITLE
[Other] How to undo the changes done to the amfi and system.

### ISSUE THREAD

**Issue by S123MR** [Kyle-Ye/XcodeLLMEligible#29]

**Comment by Kyle-Ye** [comment]
See [README.md](https://github.com/Kyle-Ye/XcodeLLMEligible?tab=readme-ov-file#method-1-util-tool-recommended-1)

> Enable SIP in recovery mode with `csrutil enable` and reboot.
> Remove boot argument by `sudo nvram -d boot-args`
