### ISSUE TITLE
[Other] No AI feature in Photo App while Apple Intelligence is activated. 

### ISSUE THREAD

**Issue by lge6** [Kyle-Ye/XcodeLLMEligible#30]
### Additional Information

Macbook Pro with Macos 15.1 Public Beta 3.  Apple Intelligence is successfully activated, and Siri with AI works fine. But AI features in Photo,such as Clean Up, are not showing up.

**Comment by Kyle-Ye** [comment]
Expected. The script has not added direct support for it.

Please check the `Manual Execution` part.

```
# For clean Up as part of Apple Intelligence feature (macOS 15.1 Beta 3+ required)
./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_STRONTIUM --answer 4
```

See https://github.com/Kyle-Ye/XcodeLLMEligible/commit/57d3feec573459d2febc3bfd44643d5706bbe407

**Comment by lge6** [comment]
Hi, I just disabled SIP and set up boot args. Then I tried to excute util files, and it says zzh:permission denied. May I ask how to sovle this? Thanks.
