### ISSUE TITLE
[Method 1] 启动参数无法添加

### ISSUE THREAD

**Issue by YISOW** [Kyle-Ye/XcodeLLMEligible#32]
### Additional Information

nvram: Error setting variable -'boot-args': (iokit/common) not permitted

**Comment by Kyle-Ye** [comment]
You need to disable SIP first.

**Comment by YISOW** [comment]
> You need to disable SIP first.

已经关了SIP了，还是出这个问题

**Comment by Kyle-Ye** [comment]
Can you provide the full output for the following commands?
```
csrutil status
sudo nvram boot-args="amfi_get_out_of_my_way=1"
```

**Comment by Kyle-Ye** [comment]
Closed due to inactivity.

**Comment by WilliamMaybe** [comment]
same question!
sudo: command not found;
without sudo is nvram: Error setting variable -'boot-args': (iokit/common) not permitted

**Comment by Kyle-Ye** [comment]
> same question! sudo: command not found; without sudo is nvram: Error setting variable -'boot-args': (iokit/common) not permitted

`sudo` is not available if you are in RecoveryOS.

Disable SIP in RecoveryOS and then reboot into normal macOS.

Run `sudo nvram boot-args="amfi_get_out_of_my_way=1"` in normal macOS and reboot again to make it taking effect.

**Comment by WilliamMaybe** [comment]
thanks
