### ISSUE TITLE
[Method 1] Seems to work on 18.2 beta1 but the image playground doesn't work

### ISSUE THREAD

**Issue by HPevensie** [Kyle-Ye/XcodeLLMEligible#35]
### Additional Information

it stays in this splash screen for a long time. I wonder it need additional command line like photo clean up does?
<img width="1012" alt="Screenshot 2024-10-24 at 1 54 28 PM" src="https://github.com/user-attachments/assets/488048fd-f1c8-41ee-b54f-14db8c88e907">

**Comment by HPevensie** [comment]
system version 15.2 beta 1 (24C5057p) sorry for the mistype

**Comment by fzlzjerry** [comment]
![CleanShot 2024-10-25 at 21 50 14@2x](https://github.com/user-attachments/assets/90ea601a-570b-4ec3-bd04-0c732b2c3c72)
I also affected this problem

**Comment by HPevensie** [comment]
I'm not sure about whether it's apple's server side problem or we haven't unlocked it. My apple intelligence size is fixed at 5.33GB

**Comment by DrJapan** [comment]
I have the splash screen removed, but every thing gives me, "Unable to use that description," error.

**Comment by HPevensie** [comment]
That won’t work. I assume that there are more content need to be downloaded before you can use the appSent from my iPhoneOn Oct 28, 2024, at 12:59 PM, TTMedia Services Inc. ***@***.***> wrote:﻿
I have the splash screen removed, but every thing gives me, "Unable to use that description," error.

**Comment by HPevensie** [comment]
I have had image playground, but I don't know where to use Genmoji and image wand

**Comment by Kyle-Ye** [comment]
The waitlist logic is out of scope of the repo. Closed it.
