### ISSUE TITLE
[Method 1] Cleanup in Photo App Doesn't Work

### ISSUE THREAD

**Issue by CharryLee0426** [Kyle-Ye/XcodeLLMEligible#37]
### Additional Information

After forcing to eligible XCodeLLM and Apple Intelligence by following method 1, I successfully enabled Apple Intelligence. Every new feature works well except the new CleanUp function in Photo App. Is it because Apple Intelligence is not installed complete yet or that function is really region strict?

**Comment by Kyle-Ye** [comment]
See manually step here. I'll update the script later since Clean up is out of beta now.

> # For clean Up as part of Apple Intelligence feature (macOS 15.1 Beta 3+ required)
./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_STRONTIUM --answer 4
