### ISSUE TITLE
[Other] Method2 all settled but something still wrong

### ISSUE THREAD

**Issue by massyzs** [Kyle-Ye/XcodeLLMEligible#38]
### Additional Information

"There may be a problem connecting to the network or server. Try again in a few minutes."

I have done following second method which does not disable sip. After doing all steps and reboot macbook, there is apple AI in the setting. But when I click join waitlist, it shows: "There may be a problem connecting to the network or server. Try again in a few minutes."

I change my apple id to Singapore from China for one day, is there anything to do with this

**Comment by Kyle-Ye** [comment]
The repo only unlocks the local framework/OS's eligibility limitation.

For Apple server related logic (Joining waitlist/changing Apple ID account etc), there is nothing we can do. 

Saying that, there is some suggested tips you can follow.

> https://github.com/Kyle-Ye/XcodeLLMEligible?tab=readme-ov-file#other-apple-intelligence-related-issue
> Use US Apple ID and English as your Siri language.
