### ISSUE TITLE
[Other] The "Clean Up" AI feature missing in Photos

### ISSUE THREAD

**Issue by FlashCarrot** [Kyle-Ye/XcodeLLMEligible#39]
Apple Intelligence is successfully activated, but there is no AI feature in Photos

<img width="547" alt="Screenshot 2024-10-30 at 6 35 29 PM" src="https://github.com/user-attachments/assets/f399a060-844b-4a4f-a85a-f89dc81096b8">

**Comment by Kyle-Ye** [comment]
See https://github.com/Kyle-Ye/XcodeLLMEligible/commit/c55a7b452a5fe1af2750253817d4bf87a8c018c1

You need an extra step ("strontium") besides "greymatter"

Unfortunately, the overrides file for it has not provided yet. So you need to use method 1.

**Comment by Kyle-Ye** [comment]
Keep this issue open until I add "strontium" support for method 2 later this week.

**Comment by GYFF-A** [comment]
Hello, which code should I use to activate the clean up feature instead of disabling SIP?

**Comment by GYFF-A** [comment]
Hello, which code should I use to activate the clean up feature without disabling SIP?

**Comment by Kyle-Ye** [comment]
They are unavailable yet.

**Comment by Kyle-Ye** [comment]
Closed by 1822bd81f7d87cbeb0fa09f78601934116771499
