### ISSUE TITLE
[Other] No such file or directory:./eligibility_util

### ISSUE THREAD

**Issue by Nudeladder** [Kyle-Ye/XcodeLLMEligible#40]
### Additional Information

I try to execute the commands following step 3 but it doesn’t work. Terminal could not find the eligibility utility file, which I had downloaded into the “Downloads” folder

**Comment by Kyle-Ye** [comment]
You need to change your working directory into Downloads first.

You can use `pwd` in terminal to show your current working directory and use `cd ~/Downloads` to change it to the “Downloads” folder.

```shell
cd ~/Downloads
./eligibility_util <arguments>
```

If you still have issue, please reopen the issue and give me the output of the following commands.

```shell
pwd
cd ~/Downloads
pwd
ls .
```

**Comment by Nudeladder** [comment]
/Users/nikoome/Downloads
$RECYCLE.BIN		dmg files		icons
desktop.ini		eligibility_util	      stuff

**Comment by Kyle-Ye** [comment]
Yes. Look you are in the correct working directory now. You can then use `./eligibility_util` without the `No such file or directory` error message.

**Comment by Nudeladder** [comment]
I used it. I said "numbers expected, permission denied"

**Comment by Kyle-Ye** [comment]
For permission issue, please refer to the step 1 and step 2

> - Disable SIP in recovery mode with `csrutil disable`
> - Add boot argument by `sudo nvram boot-args="amfi_get_out_of_my_way=1"` and reboot

You can check it by `csrutil status` and `sudo nvram boot-args`.

Note: 
1. You nee disable SIP before setting nvram boot-args
2. After set nvram boot-args, you need to reboot to make it take effect.

**Comment by Nudeladder** [comment]
![image](https://github.com/user-attachments/assets/f9629f22-2f54-4392-9155-c38c7cf7d2a0)
So I checked everything but it's still not working...

**Comment by Nudeladder** [comment]
> I did a little googling and managed to let terminal gain access by using 
"chmod 755"

**Comment by Kyle-Ye** [comment]
Yeah. 

"Permission denied" is probably due to missing `x` permission. You need to use `chmod +x ./eligibility` (or `chmod 755` will also work)

I thought you are in the security permission here. 

The error message is as following if you skip step 1 or step 2.

```
./eligibility_util
[1]    61672 killed     ./eligibility_util
```

**Comment by Kyle-Ye** [comment]
Thanks for the reporting.

Added the FAQ section.

https://github.com/Kyle-Ye/XcodeLLMEligible/commit/b03b4bfcee4ebe611cef2f37df3961e7eb632b6a
