### ISSUE TITLE
[Other] 安装后map app地图变成原生地图（而不是高德地图）导致定位偏移

### ISSUE THREAD

**Issue by Alexz986** [Kyle-Ye/XcodeLLMEligible#44]
### Additional Information

Device: MacBook Pro M2 Pro(earlier 2023) purchased in China mainland
OS: Mac OS 15.1
location: Beijing
以util方式安装apple intelligence 后，测试其他app功能时发现 map app中地图文件由高德地图文件变成了map app原生地图，导致在中国境内会有定位偏移且无法查询路线的问题

**Comment by Kyle-Ye** [comment]
1. 不清楚你是通过哪种方式进行的安装，如果是使用了 --all 可能会存在该问题，Eligibility 中有一个 key 是判断是否为大中华区来进行某些合规的文案展示和服务提供，可能会影响地图的判断，如有影响建议参照 uninstall 回滚或者仅按需覆盖 xcodellm/greymatter 即可。

> 还有一个猜想是你可能使用了 https://github.com/CatMe0w/zouxian 等方式修改了 deviceRegionCode 导致设备直接判断为了美区，可以使用 `eligibility_util getStateDump` 看下 deviceRegionCode 是否是正常的国区 `CH`

2. 据我之前所知 Map.app 的地图数据来源有高德和Tomtom，主要是根据你的网络来进行判断分流的，具体详细的规则和讨论可以参考互联网其他资料 （大部分人是希望从国内专用的高德切换到全球使用的Tomtom）

- https://www.v2ex.com/t/916465
- https://github.com/VirgilClyne/iRingo

iOS 版本左下角有明显标识，macOS 端好奇你是怎么判断出来使用了非“高德地图”的?

**Comment by Alexz986** [comment]
感谢您的回复
我只是对这个问题比较好奇，所以才咨询您。
macOS端的地图在中国大陆地区使用的地图是高德地图，在下方是有标识的。

另外安装后，news.app可以正常使用了，之前在中国境内是用不了的

**Comment by Alexz986** [comment]
我是按照您的util方案手动执行 进行安装的

**Comment by Kyle-Ye** [comment]
> 感谢您的回复 我只是对这个问题比较好奇，所以才咨询您。 macOS端的地图在中国大陆地区使用的地图是高德地图，在下方是有标识的。

用了我自己设备和其他几台设备看了下，还是没有看到 macOS 端 Map.app 使用高德地图的标注，可以截图下吗？

> 另外安装后，news.app可以正常使用了，之前在中国境内是用不了的

还是感觉你这边出现的 News.app 和 Map.app 的提供商变更变化大概率和本仓库无关。逻辑上讲不通，macOS 不太会用 GREYMATTER key 去耦合判断你上面提到的以上变更。你可以通过进行仓库提供的 util uninstall 操作后来验证实锤。

感觉还是 Apple ID / 网路 / deviceRegionCode 等变化导致的。

**Comment by Alexz986** [comment]
我对代码不是很了解，所以没办法自己研究代码，稍后我会uninstall util验证一下，在昨天安装前map.app是有显示高德地图标注的，另外，因为我之前一直在洛杉矶，所以apple ID以及所有apple设备的region都设置的是美国且系统语言是英文，不知道是否会有影响。
（稍后我会把地图截图给您）

**Comment by Alexz986** [comment]
Hi there
确实是我忽略了网络因素，刚看了一下我vpn规则，之前apple服务是direct，所以采用的地图源是高德，现在更改为全局代理，所以自动转换为原生地图了。

下图是将vpn改成direct之后map.app的现实情况

<img width="1075" alt="Screenshot 2024-11-02 at 8 27 29 PM" src="https://github.com/user-attachments/assets/4c2342ac-7773-43a1-b657-11aa2d46c80a">
<img width="878" alt="Screenshot 2024-11-02 at 8 34 54 PM" src="https://github.com/user-attachments/assets/508e97cf-2e0d-4065-95df-27264490da09">

**Comment by Alexz986** [comment]
再多问一下，在下一次系统更新后，目前安装的eligibility是否会失效、需要再次安装？

望回复，谢谢

**Comment by Kyle-Ye** [comment]
> 再多问一下，在下一次系统更新后，目前安装的eligibility是否会失效、需要再次安装？
> 
> 望回复，谢谢

苹果没有 patch 修复这个口子的话就不会
