### ISSUE TITLE
[Method 2] 中国区的apple ID 可以激活吗？

### ISSUE THREAD

**Issue by xujipm** [Kyle-Ye/XcodeLLMEligible#46]
### JSON Output

{
    "OS_ELIGIBILITY_DOMAIN_ALUMINUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_ARGON" = 2;
    "OS_ELIGIBILITY_DOMAIN_BERYLLIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_BORON" = 2;
    "OS_ELIGIBILITY_DOMAIN_CALCIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_CARBON" = 2;
    "OS_ELIGIBILITY_DOMAIN_CHLORINE" = 2;
    "OS_ELIGIBILITY_DOMAIN_CHROMIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_COBALT" = 4;
    "OS_ELIGIBILITY_DOMAIN_COPPER" = 2;
    "OS_ELIGIBILITY_DOMAIN_FLUORINE" = 2;
    "OS_ELIGIBILITY_DOMAIN_GREYMATTER" = 4;
    "OS_ELIGIBILITY_DOMAIN_HELIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_HYDROGEN" = 2;
    "OS_ELIGIBILITY_DOMAIN_IRON" = 4;
    "OS_ELIGIBILITY_DOMAIN_KRYPTON" = 2;
    "OS_ELIGIBILITY_DOMAIN_LITHIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_LOTX" = 2;
    "OS_ELIGIBILITY_DOMAIN_MAGNESIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_MANGANESE" = 2;
    "OS_ELIGIBILITY_DOMAIN_NEON" = 2;
    "OS_ELIGIBILITY_DOMAIN_NICKEL" = 2;
    "OS_ELIGIBILITY_DOMAIN_NITROGEN" = 2;
    "OS_ELIGIBILITY_DOMAIN_OXYGEN" = 2;
    "OS_ELIGIBILITY_DOMAIN_PHOSPHORUS" = 2;
    "OS_ELIGIBILITY_DOMAIN_PODCASTS_TRANSCRIPTS" = 2;
    "OS_ELIGIBILITY_DOMAIN_POTASSIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_RUBIDIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_SCANDIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_SEARCH_MARKETPLACES" = 2;
    "OS_ELIGIBILITY_DOMAIN_SILICON" = 2;
    "OS_ELIGIBILITY_DOMAIN_SODIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_STRONTIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_SULFUR" = 2;
    "OS_ELIGIBILITY_DOMAIN_SWIFT_ASSIST" = 2;
    "OS_ELIGIBILITY_DOMAIN_TITANIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_VANADIUM" = 2;
    "OS_ELIGIBILITY_DOMAIN_XCODE_LLM" = 2;
    "OS_ELIGIBILITY_DOMAIN_ZINC" = 2;
}

### Upload Compressed Archive

中国区的apple ID可以激活码，我在尝试加入waitlist的时候，报错了，不知道是不是中国区ID不支持的原因
![image](https://github.com/user-attachments/assets/c475714e-6fd8-42d4-86b2-606410dcdc1f)

**Comment by Kyle-Ye** [comment]
符合预期。

中国大陆的Apple ID无法通过 waitlist 校验，需要切换 Apple ID 账号到支持的区域(eg. 美区)，具体流程参考[这里](https://github.com/Kyle-Ye/XcodeLLMEligible/blob/main/README.md#other-apple-intelligence-related-issue)
