### ISSUE TITLE
[Other] eligibility-intel

### ISSUE THREAD

**Issue by DrJapan** [Kyle-Ye/XcodeLLMEligible#48]
### Additional Information

Has anyone been able to get this to complete, on an Intel machine?

https://github.com/saulcheeseman/eligibility-intel

**Comment by Kyle-Ye** [comment]
I guess Apple intelligence and Xcode LLM is not supported on intel machine.

But you can still use it(`eligibility_util`) to unlock other non-functional stuff on intel machine.

**Comment by DrJapan** [comment]
What else could be unlocked?
