### ISSUE TITLE
[Method 1]  - New PLIST with authorized Devices

### ISSUE THREAD

**Issue by DrJapan** [Kyle-Ye/XcodeLLMEligible#50]
### Additional Information

It appears that in /System/Library/PrivateFramworks/Anvil.Framework/AuthorizedDevices.plist is somehow blocking access to AI.

**Comment by Kyle-Ye** [comment]
What problem are you encountering?

I know such addition in the new OS.

But I have not confirmed the logic with eligibility related service.

Are you reporting you have a old device out of AuthorizedDevices.plist and can't unlock XcodeLLM or Apple Intelligence here?

**Comment by Kyle-Ye** [comment]
Close due to inactivity.

**Comment by DrJapan** [comment]
Yes. My MacBook Pro with Intel used to be able to download models, but now it's just stuck on preparing.
