### ISSUE TITLE
[Other] Macos 15.2 Some AI features are enabled. 

### ISSUE THREAD

**Issue by lge6** [Kyle-Ye/XcodeLLMEligible#51]
### Additional Information

I unlocked the AI features(by disabling SIP) in Macos 15.1, and then upgraded to Macos 15.2. Recently I got the access to the Image Playground. However, it seems that I cannot see genmoji options when I use emoji keyboard. Maybe need to wait for a updates?

**Comment by Kyle-Ye** [comment]
I'll confirm it later this week.

**Comment by Kyle-Ye** [comment]
Expected. It is only available on iPhone now. Maybe Apple will fix/support it in later release of macOS.
 https://www.reddit.com/r/MacOSBeta/comments/1gm8ojh/i_got_access_to_image_playground_finally_on_my/
