### ISSUE TITLE
如何彻底卸载 Apple Intelligence呢？

### ISSUE THREAD

**Issue by Kalpeny** [Kyle-Ye/XcodeLLMEligible#53]
### Additional Information

试用后感觉不是很好用，占用4.4G的空间，如何彻底卸载Apple Intelligence？
![image](https://github.com/user-attachments/assets/e97ae92e-ba6d-43c4-b6f2-d3c6d613217f)

**Comment by Kyle-Ye** [comment]
Basically, this is out of scope of the repo. And I do not know and is not responsible for such answer.

If you want to restore to previous/default eligibility status for Apple Intelligence, you can follow the uninstall step in README.md.

For removing the Apple Intelligence model data, you can search it on Internet or ask in Apple forums. eg. https://discussions.apple.com

**Comment by Kyle-Ye** [comment]
Search it for you:

Just turn off the Apple Intelligence option in Setting, and the OS will auto delete it after one week. Or if you are eager, you can just do a clear OS install.

> Source: https://www.reddit.com/r/ios18beta/comments/1ftpmch/how_i_can_remove_apple_intelligence_data/

**Comment by Lessica** [comment]
我这边发生了一个问题。在旧版本 macOS 上使用此工具打开了，但更新到了新版本 macOS，功能无法使用了，但原来下载的这些资源也无法清理掉了，就可能一直占用存储空间。

当然并不是说和这个 repo 有什么强关联，也不是说要求作者来做什么事情… 只是讨论下该如何解决，毕竟苹果的存储还挺贵的，重做系统也挺麻烦。

我打算参考这个来解决，暂时不知道靠不靠谱：https://www.reddit.com/r/MacOS/comments/1hca5ap/how_do_i_remove_apple_intelligence_permanently

**Comment by Kyle-Ye** [comment]
1. `rm -rf` should work as the post's reply.
2. If it is not work, you can try enter Recovery mode, mount the Volumn and then try delete it if you do not have the permission in a normal macOS environment.
