### ISSUE TITLE
bad CPU type in executable: ./eligibility_util_sip

### ISSUE THREAD

**Issue by djpetere** [Kyle-Ye/XcodeLLMEligible#54]
### Additional Information

Unfortunately the trick does not work on mac with intel processor.
You need to add a bypass for checking the processor version.

/eligibility_util_sip forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER --answer 4
zsh: bad CPU type in executable: ./eligibility_util_sip

**Comment by Kyle-Ye** [comment]
Expected behavior. I certainly can compile a x86_64 version for eligibility_util and make it as an universal binary.

But both XcodeLLM and Apple Intelligence will not work on intel ones even you managed to enable them using this repo's solution.

See #48 for more information.
