### ISSUE TITLE
[Other] 

### ISSUE THREAD

**Issue by baobaotql** [Kyle-Ye/XcodeLLMEligible#55]
### Additional Information

Unable to join waitlist
There may be a problem connecting to the network or server. Try again in a few minutes.

**Comment by Kyle-Ye** [comment]
1. Use non-China mainland Apple ID
2. Use a proper network/VPN env

**Comment by baobaotql** [comment]
maybe i should change a vpn

**Comment by Kyle-Ye** [comment]
If you use an unsupported country's Apple ID (eg. China mainland), you'll always get such error even you use a US VPN.

So you need to log in a US apple ID first and then try it with a US VPN environment.

**Comment by FirmamentWu** [comment]
<img width="260" alt="Snipaste_2025-01-12_19-01-08" src="https://github.com/user-attachments/assets/0c8e46c8-1bfc-4522-9fcd-9826f3118721" />
你们遇到这个问题了么

**Comment by Kyle-Ye** [comment]
Try to use a global US network (VPN)
