### ISSUE TITLE
[Other] m4 mac mini 禁用sip后无限重启

### ISSUE THREAD

**Issue by CoderGFWu** [Kyle-Ye/XcodeLLMEligible#57]
### Additional Information

m4 mac mini 禁用sip后无限重启， 输完密码进入桌面， 几秒后自动重启， 进入死循环， 如果停留在输密码的页面不会重启

**Comment by fzlzjerry** [comment]
sip禁用后重启不能算这个的bug吧

**Comment by Kyle-Ye** [comment]
If you have issue disabling SIP, you can just reenable it in Recovery mode.

Saying that, you should inspect which part of your OS is causing the crash when SIP is disabled. (Out of scope of this repo)
