### ISSUE TITLE
[Other] Update script for the latest 15.2 update

### ISSUE THREAD

**Issue by CharryLee0426** [Kyle-Ye/XcodeLLMEligible#58]
### Additional Information

System: macOS 15.2 official release;
Device: MacBook Pro M1 2020;

Proposal:
The script works well for me to activate XCodeLLM, Apple Intelligence, and Image Cleanup on macOS 15.1. However, I can't use the new Playground app after updating to 15.2. ChatGPT extension works well after updating to 15.2. So I think the current script needs to be updated to enable Playground app.

**Comment by CharryLee0426** [comment]
Playground app is new feature only available on macOS 15.2 or later.

**Comment by ernestyao** [comment]
I ran the script for Apple Intelligence after updating macOS 15.2 official release. Playground and ChatGPT extension both work well. I suppose rerunning the script may solve the problem.

**Comment by RisenL** [comment]
Apple Intelligence Photo Clean Up is not working.

**Comment by hyderay** [comment]
Everything works fine. If u r  stuck on downloading, maybe try to delete all contents within /System/Library/AssetsV2/ and re-enable the apple intelligence.

**Comment by CharryLee0426** [comment]
> Everything works fine. If u r stuck on downloading, maybe try to delete all contents within /System/Library/AssetsV2/ and re-enable the apple intelligence.

Hi, I tried but I couldn't delete this folder even with sudo

**Comment by CharryLee0426** [comment]
Updates: rerunning the script and restarting the Mac work. For the first time, it takes longer time to generate images due to initialization. No need to change the script in fact.
