### ISSUE TITLE
[Other] Downloading 15.2 failed due to internet connection

### ISSUE THREAD

**Issue by Ryanwu316** [Kyle-Ye/XcodeLLMEligible#59]
### Additional Information

I’ve tried downloading version 15.2 several times, but it keeps failing  a network error. However, my internet connection is stable. Please help.<img width="260" alt="image" src="https://github.com/user-attachments/assets/6c31a4aa-2c9c-4d7d-b9db-7edb845127bb" />

**Comment by Belonng** [comment]
@Ryanwu316 How did you solve this network problem? I'm having the same problem.
