### ISSUE TITLE
最新使用结果反馈

### ISSUE THREAD

**Issue by yunluoxin** [Kyle-Ye/XcodeLLMEligible#6]
### Additional Information

昨晚升级了macOS 15.0 beta 4，使用脚本+plist 成功开启。
今早起来，macOS 15.1 出来了。升级后：
macOS 15.1 使用脚本失效
Xcode 设置中，提示 <img width="865" alt="image" src="https://github.com/user-attachments/assets/7eca67cd-c234-4683-acf1-66d737f43ed1">
使用脚本后，也是不行。

**Comment by Kyle-Ye** [comment]
Please use issue template to reopen your issue or update your content directly to include the necessary information.

**Comment by fmatrixch** [comment]
> ### Additional Information
> 
> 昨晚升级了macOS 15.0 beta 4，使用脚本+plist 成功开启。 今早起来，macOS 15.1 出来了。升级后： macOS 15.1 使用脚本失效 Xcode 设置中，提示 <img alt="image" width="865" src="https://private-user-images.githubusercontent.com/15810095/353330561-7eca67cd-c234-4683-acf1-66d737f43ed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1Njc1MDgsIm5iZiI6MTcyMjU2NzIwOCwicGF0aCI6Ii8xNTgxMDA5NS8zNTMzMzA1NjEtN2VjYTY3Y2QtYzIzNC00NjgzLWFjZjEtNjZkNzM3ZjQzZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDAyNTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZWZmZjJkMTJlMmNkNzc3ZjM3MDMwYTYwZWUwNTZlZmZhNDNhZmM1ODVkMGNhNjNkYzFhMWQ2ODc1NGZkMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vTJMRdiy99F_sBV5kCO_vDkts3kc6tr7Ra-7FZaW3Ig"> 使用脚本后，也是不行。

我觉得脚本有问题 建议不要用开发者的脚本。

按照Method 1走成功率最高

**Comment by Kyle-Ye** [comment]
> 我觉得脚本有问题 建议不要用开发者的脚本。
> 
> 按照Method 1走成功率最高

No. They are the same.

The script just choose to perform method 1 or method 2 automatically according to your status. (If you have SIP disable + boot-args set -> Method 1. Otherwise method 2).

Read the script output carefully.

And method 2 has known issue in the readme.

So you should disable SPI & set boot-args and then perform method 1 manually or run the script.
