### ISSUE TITLE
[Other]  Downloading LLM stuck at 100%.

### ISSUE THREAD

**Issue by Ryanwu316** [Kyle-Ye/XcodeLLMEligible#61]
### Additional Information

I keep getting stuck at 100% when downloading the model.
![WX20241213-105449@2x](https://github.com/user-attachments/assets/95bc8701-cf58-4e7e-bbb5-4e591014a9a1)

**Comment by Ryanwu316** [comment]
Then I restart my mac, it downloads again from the begaining.

**Comment by Kyle-Ye** [comment]
Maybe you can try this:

https://github.com/Kyle-Ye/XcodeLLMEligible/issues/62#issuecomment-2541993096

**Comment by Kyle-Ye** [comment]
You can also try the detailed instruction updated in the latest FAQ.

https://github.com/Kyle-Ye/XcodeLLMEligible/commit/c9a105a96fc80ca3750c57872cf1f79fb54b0cf8
