### ISSUE TITLE
[Method 1] Mac mini m4 macOS 15.2 stuck on downloading

### ISSUE THREAD

**Issue by achenjiefeng** [Kyle-Ye/XcodeLLMEligible#62]
### Additional Information

After multiple attempts to install and uninstall, it still hasn't worked and remains stuck on "downloading." Does anyone know how to solve this?
![1](https://github.com/user-attachments/assets/c70470ca-c36c-4577-9554-fd4200cddc76)

**Comment by Kyle-Ye** [comment]
Make sure you have a valid Internet connection.

There may have some network limitation for China mainland network.

**Comment by achenjiefeng** [comment]
> Make sure you have a valid Internet connection.
> 
> There may have some network limitation for China mainland network.

Thank you for your response. I have found the cause of the issue. It seems to be due to not properly uninstalling leftover files earlier. After deleting all the files in the AssetsV2 folder, I was able to install it correctly.

**Comment by XhivaW** [comment]
> > Make sure you have a valid Internet connection.
> > There may have some network limitation for China mainland network.
> 
> Thank you for your response. I have found the cause of the issue. It seems to be due to not properly uninstalling leftover files earlier. After deleting all the files in the AssetsV2 folder, I was able to install it correctly.

Hi, I meet the same situation and just wonder how to delete files in /System/Library/AssetsV2 folder as the terminal shows "Read-only file system" when SIP is disabled

**Comment by Kyle-Ye** [comment]
> Hi, I meet the same situation and just wonder how to delete files in /System/Library/AssetsV2 folder as the terminal shows "Read-only file system" when SIP is disabled

You need to disable SIP to delete it. See the latest README's FAQ part.

**Comment by XhivaW** [comment]
> > Hi, I meet the same situation and just wonder how to delete files in /System/Library/AssetsV2 folder as the terminal shows "Read-only file system" when SIP is disabled
> 
> You need to disable SIP to delete it. See the latest README's FAQ part.

Hi, the SIP is disabled as FAQ part says, but it still shows "Read-only file system" for several sub folder

**Comment by mietl** [comment]
> > Hi, I meet the same situation and just wonder how to delete files in /System/Library/AssetsV2 folder as the terminal shows "Read-only file system" when SIP is disabled
> 
> You need to disable SIP to delete it. See the latest README's FAQ part.

@Kyle-Ye I can't delete it after it is disabled.

**Comment by Kyle-Ye** [comment]
See https://www.reddit.com/r/MacOSBeta/comments/1eqrg3k/comment/lnriaea/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

I have also updated the README to make it more clear.

@XhivaW @mietl

**Comment by XhivaW** [comment]
> See https://www.reddit.com/r/MacOSBeta/comments/1eqrg3k/comment/lnriaea/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
> 
> I have also updated the README to make it more clear.
> 
> > Tested it under my M1 and M4 Pro machine. Have no problem deleting the files in AssetsV2.
> 
> @XhivaW @mietl

Thx for ur reply. I think the `csrutil authenticated-root disable` is missed in my case, will try later and update result here.
Thx again.

**Comment by Kyle-Ye** [comment]
Also remember to `rm` the `AssetsV2/*` instead of `AssetsV2` since `AssetsV2` folder itself is readonly and can't be deleted.

**Comment by achenjiefeng** [comment]
> Also remember to `rm` the `AssetsV2/*` instead of `AssetsV2` since `AssetsV2` folder itself is readonly and can't be deleted.

At first, I also tried using rm to delete the assetsV2, but it failed every time near the end of the process. For some people, you need to manually open the folder and move all the files inside to the trash. The rm command cannot remove all the files since some require authorization and password input to uninstall.

**Comment by Kyle-Ye** [comment]
> > Also remember to `rm` the `AssetsV2/*` instead of `AssetsV2` since `AssetsV2` folder itself is readonly and can't be deleted.
> 
> At first, I also tried using rm to delete the assetsV2, but it failed every time near the end of the process. For some people, you need to manually open the folder and move all the files inside to the trash. The rm command cannot remove all the files since some require authorization and password input to uninstall.

Yeah. Use "Finder to delete" or "`csrutil authenticated-root disable` and then `rm`" both worked for me.

**Comment by XhivaW** [comment]
> > > Also remember to `rm` the `AssetsV2/*` instead of `AssetsV2` since `AssetsV2` folder itself is readonly and can't be deleted.
> > 
> > 
> > At first, I also tried using rm to delete the assetsV2, but it failed every time near the end of the process. For some people, you need to manually open the folder and move all the files inside to the trash. The rm command cannot remove all the files since some require authorization and password input to uninstall.
> 
> Yeah. Use "Finder to delete" or "`csrutil authenticated-root disable` and then `rm`" both worked for me.

Hi, here is the update:
1. with `csrutil authenticated-root disable` I can empty assetsV2 folder successfully
2. ONLY choosing English(United States) as Siri language, Apple Intelligence can be load successfully. And I cannot change to other language as Apple Intelligence will immediately deactivate.
Just wonder if it's possible to choose other language?

**Comment by Kyle-Ye** [comment]
> 2. ONLY choosing English(United States) as Siri language, Apple Intelligence can be load successfully. And I cannot change to other language as Apple Intelligence will immediately deactivate.
>    Just wonder if it's possible to choose other language?

Only part language is supported for now. And Apple will expand other language supported gradually in future OS update. This is not an issue I can help.
