### ISSUE TITLE
[Other] 有没有被AI引导去用百度查找的？

### ISSUE THREAD

**Issue by lesliehua** [Kyle-Ye/XcodeLLMEligible#64]
### Additional Information

有没有人的AI反馈回答是推荐用百度查找的？并且还在回复的末尾给了一个大大的蓝色“百度查找”的按钮～太奇怪了，我查看了我的Safari、edge默认查找引擎都是google的

**Comment by Kyle-Ye** [comment]
Please see 4 of the FAQ.
