### ISSUE TITLE
[Method 1] Assuming Apple has blocked external system disks?

### ISSUE THREAD

**Issue by orangeX21** [Kyle-Ye/XcodeLLMEligible#66]
### Additional Information

Problem Analysis
	1.	Phenomenon Description:
	•	Stuck during the process of using Solution 2 with the override file.
	•	Issues encountered with the external system disk.
	•	After downloading a 5.06GB update package, there is no response, and the Siri settings display “Downloading” for an extended period.
	•	SIP (System Integrity Protection) has been disabled, and the AssetsV2 folder has been deleted.
	2.	Known Environment:
	•	Hardware: MacBook (ARM64 architecture, macOS 15.3).
	•	Anomalies specifically occur with the external system disk.
	3.	Possible Causes:
	•	External System Disk Restrictions: macOS 15 introduced stricter limitations on external system disks.
	•	System Integrity Protection (SIP) Impact: Disabling SIP might have caused certain system functions to not execute properly.
	•	Network Environment/Apple Server: The lack of response after downloading could be related to caching or validation issues.

Following the tutorial, the process remains stuck at this stage.
<img width="496" alt="2024-12-30 下午8 33 20" src="https://github.com/user-attachments/assets/cf33dd78-3376-4756-9a71-045640cba418" />
At the same time, after disabling SIP, I deleted the AssetsV2 folder. Through packet capture, I observed a download of approximately 5.06GB from updates.cdn-apple.com.
<img width="270" alt="2024-12-30 下午8 39 39" src="https://github.com/user-attachments/assets/4bbe992f-3300-46d6-a8ab-0cfebd1bf737" />
After the download was completed, there was still no response. The Siri settings remained stuck showing “Downloading” for a week.

Meanwhile, I noticed a phenomenon: it seems Apple has restricted the use of external system disks.

If this is the case, is there a good solution? My notebook system is separated for personal and work use, so I need to experience it on the external system disk!

**Comment by Kyle-Ye** [comment]
The eligibility system and other parts of macOS have some restriction when you boot the OS from an external storage.

I do not know the exact reason for it. Maybe you can check Setting's app log or binary if you have the energy. But an easier solution is just not use external storage if you want to try the AI feature.

> My notebook system is separated for personal and work use, so I need to experience it on the external system disk!

You can add a separate APFS volume to install another macOS for your personal use and remain your work's macOS unaffected.

The only limitation is that you need to have enough remaining storage for it.(50GB+) 

<img width="1222" alt="image" src="https://github.com/user-attachments/assets/0d5af4e2-5c70-4a19-ad11-6fa00a027701" />

**Comment by samixp02** [comment]
I was able to run apple intelligence without a problem of course I have edited eligibility.plist or using the methods in this repo 
anyway what I wanted to say is that the size will exceed 9 GB if I'm not wrong
