### ISSUE TITLE
[Method 1] 没有解锁apple intelligence

### ISSUE THREAD

**Issue by zhenniqi** [Kyle-Ye/XcodeLLMEligible#7]
首先尝试使用了method2，包括#3中的方法，解锁apple intelligence失败后采用method1，关闭了sip和amfi，最终还是没有解锁apple intelligence[Method 1] 

### Additional Information

curl -L https://raw.githubusercontent.com/Kyle-Ye/XcodeLLMEligible/main/override_xcodellm.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4359  100  4359    0     0  12162      0 --:--:-- --:--:-- --:--:-- 12175
Performing install action...

SIP is disabled.

amfi_get_out_of_my_way=1 is present in boot-args.
🎉 SIP is disabled and amfi_get_out_of_my_way=1 is present in boot-args.

Downloading eligibility_util...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1530k  100 1530k    0     0   528k      0  0:00:02  0:00:02 --:--:-- 2506k
Setting XcodeLLM to eligible...
Force domain answer successfully
Setting Complete...

Checking the status...
OS_ELIGIBILITY_ANSWER_ELIGIBLE

XcodeLLM eligible override script install completed.
If you find this script helpful, please consider give a star to the project.
🌟🌟🌟 https://github.com/Kyle-Ye/XcodeLLMEligible 🌟🌟🌟

**Comment by Kyle-Ye** [comment]
Are you reporting an issue on Xcode LLM or Apple Intelligence?

> Checking the status...
> OS_ELIGIBILITY_ANSWER_ELIGIBLE

The log is showing that you have unlock Xcode LLM successfully. So I assume you are trying to unlock Apple Intelligence.

The repo is mainly for Xcode LLM related stuff. Saying that, the trick to unlock Xcode LLM and Apple Intelligence on unsupported device/region is the same: Method 1

For Xcode LLM
```
./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_XCODE_LLM --answer 4
```

For Apple Intelligence
```
./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER --answer 4
```

If you have further issue, you can also try #5 and use Qianli-Ma's fork.

**Comment by zhenniqi** [comment]
再一次运行了./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER --answer 4，未重启就发现Apple intelligence已经成功被解锁，非常感谢。

**Comment by Kyle-Ye** [comment]
> 再一次运行了./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER --answer 4，未重启就发现Apple intelligence已经成功被解锁

Yeah. This is expected.

> 非常感谢。

You are welcome. A star would be appreciated.
