### ISSUE TITLE
[Method 1] Is it required to use non China mainland apple account to join the the AI waitlist?

### ISSUE THREAD

**Issue by ItsRyanWu** [Kyle-Ye/XcodeLLMEligible#8]
### Additional Information

I have run all steps in method 1 and I can enter the AI settings panel in preference, however when I click join there's no response from the UI.
I've already used English(US) and switched region to US but I'm still using China region apple account on the device.

**Comment by limingyi1225** [comment]
yes

**Comment by Kyle-Ye** [comment]
Such logic is controlled by Apple Server and may change over time.

I guess the answer is yes for now.

Close due to out of scope of this repo.

**Comment by fmatrixch** [comment]
> ### Additional Information
> 
> I have run all steps in method 1 and I can enter the AI settings panel in preference, however when I click join there's no response from the UI. I've already used English(US) and switched region to US but I'm still using China region apple account on the device.

Yes.

non-Chinese mainland Apple Account is required to join the Apple Intelligence waitlist.

Actually, I have a United States Apple Account, the system region is set as United States, but I'm using English (UK) as my system language (except Siri), and I couldn't join the waitlist until I changed my system language as English (US).
