### ISSUE TITLE
[Other] Joined waitlist后5小时依然waitlist

### ISSUE THREAD

**Issue by limingyi1225** [Kyle-Ye/XcodeLLMEligible#9]
### Additional Information

网络没有问题，家里有软路由，多个国家都尝试过

**Comment by Kyle-Ye** [comment]
1. Such logic is controlled by Apple Server and may change over time. We can do nothing for it.

2. I suggest you use a US store Apple ID and change your device locale and Siri locale to en-US.

3. There may a outage for Apple's Server and they reject new user joining.

**Comment by taozhiyuai** [comment]
等了一夜,还是不行 :(

**Comment by Kyle-Ye** [comment]
See "Trouble Shooting" section:

- Log in with a US Apple ID
- Set Region to United States and English as the primary language
- Set English (United States) as your Siri language
